### ISSUE TITLE
Can we have a version of this that has no limits?

### ISSUE THREAD

**Issue by PalpatineSWU** [Allen-Wrench/NoForcedCameraZoom#2]
In a previous version of this plugin we had the ability to zoom all the way into a cockpit and through any object. 
Can we get a version of this posted that has that available? 
I am speaking on behalf of about 10 people who all use your plugin and have noticed this change, we just had a group conversation that brought it up and we all wanted the old version back. 
Thank you for this aside from wanting previous version. This plugin helps gameplay sooooooo much.

**Comment by Cabu** [comment]
I and a friend are building a space elevator. Hving no limits in the zoom in/out would be greatly appreciated because We are so zoom out right now that we can barely see the blocks because we are so far :(

**Comment by Allen-Wrench** [comment]
The reason I removed that feature was because it was too buggy and frequently cause crashes. I would like to re-implement it at some time, but I just don't have the time right now. It is on my list of things to do however.
