### ISSUE TITLE
Plug-in causing crash?

### ISSUE THREAD

**Issue by CamT189** [Allen-Wrench/NoForcedCameraZoom#4]
Hello, this is a new development for me. The only thing that's changed since I started using this plug-in was the most recent DLC. attached is the log, hopefully it helps solve the issue. Thanks

[nozoomerrorlog.txt](https://github.com/Allen-Wrench/NoForcedCameraZoom/files/12491754/nozoomerrorlog.txt)

**Comment by axxapy** [comment]
Apparently fixed in https://github.com/Allen-Wrench/NoForcedCameraZoom/pull/3

**Comment by khamseen** [comment]
Figured this plugin would have issues after the update since they changed how the game handles third person camera. Hopefully the pull request gets merged in soon.

**Comment by CamT189** [comment]
> 

i thought so too, but this error happened after the 'fix'

**Comment by bunio80** [comment]
I hope the author will fix this, I'm very used to this plugin :)

**Comment by Allen-Wrench** [comment]
I've merged the fix from Bush, let me know if there are still any issues. I've just been busy IRL with work, but I'll make some time to get this fixed if I need to.
