### ISSUE TITLE
Del-End-PgDwn don't work with left Ctrl+Shift

### ISSUE THREAD

**Issue by stevenmu2** [Allen-Wrench/NoForcedCameraZoom#6]
Not really an issue, but I wanted to share in case others experience the same.

For me, when I use the left Ctrl+Shift on my keyboard, the Del, End and PgDwn keys don't do anything, though the Ins, Home and PgUp keys do. But if I use the right Ctrl+Shift keys, then all the manipulation keys work as expected.

Regular block manipulation works ok all the time and I don't have any custom keybinds or anything.

**Comment by Allen-Wrench** [comment]
Its programmed to accept the input from any ctrl or shift keypress, so maybe another piece of software is interfering? Im not sure why that is happening.
